version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  vet:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/dianelooney/ferry
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go vet
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/dianelooney/ferry
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: mkdir /tmp/coverage
      - run: go test -race -v ./... -coverprofile=/tmp/coverage/c.out
      - run: go tool cover -html=/tmp/coverage/c.out -o /tmp/coverage/c.html
      - store_artifacts:
          path: /tmp/coverage
      - codecov/upload:
          file: /tmp/coverage/c.out
workflows:
  version: 2
  workflow:
    jobs:
    - vet
    - test
